--- #YAML:1.0
name:               MojoX-Automata-AsGraph
version:            0.02
abstract:           Create a graph from a MojoX::Automata object
author:
    - Viacheslav Tikhanovskii <vti@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Graph::Easy:      0
    MojoX::Automata:  0.500
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
